from __future__ import annotations

from datetime import UTC, datetime

from hunter.evidence_intelligence import PredicateDefinition, PredicateRegistry

COMPETITIVE_PREDICATE_SCHEMA_VERSION = "competitive-predicate-v1"


def competitive_predicate_definitions(
    *,
    schema_version: str = COMPETITIVE_PREDICATE_SCHEMA_VERSION,
    created_at: datetime | None = None,
) -> tuple[PredicateDefinition, ...]:
    created = created_at or datetime.now(tz=UTC)
    return (
        PredicateDefinition(
            predicate_id="competes_with",
            name="competes with",
            description="Two economic entities explicitly compete in a defined market, product, or use-case scope.",
            schema_version=schema_version,
            permitted_subject_types=("project", "protocol", "product", "company", "chain"),
            permitted_object_entity_types=("project", "protocol", "product", "company", "chain"),
            requires_object_entity=True,
            direction="bidirectional",
            symmetric=True,
            asymmetric=False,
            valid_qualifiers=("chain", "market", "product", "scope", "use_case"),
            valid_modalities=("asserted", "historical"),
            valid_polarities=("positive", "negative"),
            graph_projection_eligible=True,
            predicate_specific_conflict_rules="Conflicts require same subject, object, scope, modality, and overlapping validity period with opposite polarity or retraction.",
            scope_requirements="A scope, market, product, or use-case qualifier is required before interpreting competition.",
            support_requirements="Requires explicit evidence that the entities compete; co-mention is insufficient.",
            authority_requirements="Prefer official, governance, repository, or validated Hunter evidence.",
            created_at=created,
        ),
        PredicateDefinition(
            predicate_id="substitutes_for",
            name="substitutes for",
            description="One entity is explicitly positioned as a substitute for another entity or product.",
            schema_version=schema_version,
            permitted_subject_types=("project", "protocol", "product", "company", "chain"),
            permitted_object_entity_types=("project", "protocol", "product", "company", "chain"),
            requires_object_entity=True,
            direction="subject_to_object",
            inverse_predicate="substituted_by",
            symmetric=False,
            asymmetric=True,
            valid_qualifiers=("chain", "market", "product", "scope", "use_case"),
            valid_modalities=("asserted", "planned", "historical"),
            valid_polarities=("positive", "negative"),
            graph_projection_eligible=True,
            predicate_specific_conflict_rules="Different products, chains, or use cases are compatible unless scopes overlap.",
            support_requirements="Requires explicit substitute language or validated claim support.",
            created_at=created,
        ),
        PredicateDefinition(
            predicate_id="same_category_as",
            name="same category as",
            description="Two entities are explicitly categorized together by validated evidence.",
            schema_version=schema_version,
            permitted_subject_types=("project", "protocol", "token", "product", "chain"),
            permitted_object_entity_types=("project", "protocol", "token", "product", "chain"),
            requires_object_entity=True,
            direction="bidirectional",
            symmetric=True,
            asymmetric=False,
            valid_qualifiers=("category", "provider", "taxonomy"),
            valid_modalities=("asserted", "historical"),
            valid_polarities=("positive",),
            graph_projection_eligible=True,
            predicate_specific_conflict_rules="Category differences are not conflicts unless same taxonomy and scope are mutually exclusive.",
            support_requirements="Does not imply competition without a separate competition or substitution claim.",
            created_at=created,
        ),
        PredicateDefinition(
            predicate_id="same_use_case_as",
            name="same use case as",
            description="Two entities share a validated use-case scope.",
            schema_version=schema_version,
            permitted_subject_types=("project", "protocol", "token", "product", "chain"),
            permitted_object_entity_types=("project", "protocol", "token", "product", "chain"),
            requires_object_entity=True,
            direction="bidirectional",
            symmetric=True,
            asymmetric=False,
            valid_qualifiers=("market", "product", "scope", "use_case"),
            valid_modalities=("asserted", "historical"),
            valid_polarities=("positive",),
            graph_projection_eligible=True,
            predicate_specific_conflict_rules="Use-case differences are scoped facts, not automatic conflicts.",
            support_requirements="Does not imply competition without a separate competition or substitution claim.",
            created_at=created,
        ),
        PredicateDefinition(
            predicate_id="targets_market_segment",
            name="targets market segment",
            description="An entity targets a market segment represented as a typed literal.",
            schema_version=schema_version,
            permitted_subject_types=("project", "protocol", "product", "company", "chain"),
            permitted_literal_value_types=("string", "enum"),
            allows_literal_value=True,
            direction="subject_to_object",
            valid_qualifiers=("market", "region", "user_segment"),
            valid_modalities=("asserted", "planned", "historical"),
            valid_polarities=("positive", "negative"),
            graph_projection_eligible=False,
            predicate_specific_conflict_rules="Different market segments are compatible unless the same scoped segment is explicitly negated.",
            created_at=created,
        ),
        PredicateDefinition(
            predicate_id="uses_technology",
            name="uses technology",
            description="An entity uses a technology, standard, chain, or infrastructure dependency.",
            schema_version=schema_version,
            permitted_subject_types=("project", "protocol", "product", "chain"),
            permitted_object_entity_types=("standard", "chain", "protocol", "product"),
            requires_object_entity=True,
            direction="subject_to_object",
            valid_qualifiers=("deployment", "scope", "version"),
            valid_modalities=("asserted", "planned", "historical", "deprecated"),
            valid_polarities=("positive", "negative"),
            graph_projection_eligible=True,
            predicate_specific_conflict_rules="Technology use is scoped by version, deployment, and validity period.",
            created_at=created,
        ),
        PredicateDefinition(
            predicate_id="centralized_incumbent_of",
            name="centralized incumbent of",
            description="A centralized entity is explicitly identified as an incumbent for a decentralized use case or product.",
            schema_version=schema_version,
            permitted_subject_types=("company", "product"),
            permitted_object_entity_types=("project", "protocol", "product", "market"),
            requires_object_entity=True,
            direction="subject_to_object",
            valid_qualifiers=("market", "product", "scope", "use_case"),
            valid_modalities=("asserted", "historical"),
            valid_polarities=("positive", "negative"),
            graph_projection_eligible=True,
            predicate_specific_conflict_rules="Incumbent relationships require matching market or product scope.",
            support_requirements="Requires explicit evidence; broad industry presence is insufficient.",
            created_at=created,
        ),
    )


def competitive_predicate_registry(
    *,
    schema_version: str = COMPETITIVE_PREDICATE_SCHEMA_VERSION,
    created_at: datetime | None = None,
) -> PredicateRegistry:
    return PredicateRegistry(
        schema_version=schema_version,
        predicates=competitive_predicate_definitions(schema_version=schema_version, created_at=created_at),
    )
